### ISSUE TITLE
[Feature Request] Support Requesting Multiple Images (Multi-URI)

### ISSUE THREAD

**Issue by vahidvdn** [nativescript-community/ui-image#10]
Is there any way to have Multiple Images (Multi-URI)? As [native plugin](https://frescolib.org/docs/requesting-multiple-images.html) supports it.

I want to first load a smaller image, then show a high-resolution image. Any idea?

**Comment by farfromrefug** [comment]
@vahidvdn wont come soon as there is no counterpart on iOS. 
Could bring a callback though for you to do what you want with the native controller before it is applied.

**Comment by vahidvdn** [comment]
@farfromrefug Thanks for the reply.
I have a workaround mentioned [here](https://github.com/NativeScript/nativescript-fresco/issues/106) , but has a lot of problems in list views.
