### ISSUE TITLE
All Images appear upside down in IOS Only 

### ISSUE THREAD

**Issue by anaszgh** [nativescript-community/ui-image#21]
Platform: IOS
CLI Version: 5.4.2
Core Modules Version: 5.2.0

Issue:

All images using NSImage appear in Upside down only on IOS, on android they appear normally

Usage:
```
      <NSImg
        roundedCornerRadius="50"
        roundBottomRight="true"
        roundBottomLeft="true"
        roundTopLeft="true"
        roundTopRight="true"
        row="2"
        [src]="loadBanner()"
        stretch="aspectFit"
        class="banner-home-image"
      ></NSImg>
```

![Simulator Screen Shot - iPhone 6 - 2019-11-21 at 09 21 34](https://user-images.githubusercontent.com/4104274/69306282-5adb8e80-0c40-11ea-9dbf-e4fb4808ae3d.png)

**Comment by anaszgh** [comment]
The error disappear when you remove the `roundAsCircle= "true"` or 
```
        roundedCornerRadius="50"
        roundBottomRight="true"
        roundBottomLeft="true"
        roundTopLeft="true"
        roundTopRight="true"
```

**Comment by farfromrefug** [comment]
@anaszgh this issue was fixed quite some time ago. Are you using the latest plugin version? Is your cocoapod repo up to date? (to get a recent version of SDWebImage)
