### ISSUE TITLE
Compatibility with iOS 14

### ISSUE THREAD

**Issue by mmeven** [nativescript-community/ui-image#29]
Hi,
Using the plugin on iOS 14 currently results in pictures not being displayed at all.

I had a look at the changelog of the iOS plugin used underneath (SDWebImage), it seems that they fixed the issue in the last versions : [Changelog](https://github.com/SDWebImage/SDWebImage/releases)

And indeed, setting manually the version to >= 5.8.3 in the Podfile fixes the issue, at least in the apps I'm working on.

Would you have a look at it ?

Thanks in advance

**Comment by romandragan** [comment]
We're experiencing this issue https://github.com/NativeScript/NativeScript/issues/8869 with the latest version of the plugin.

**Comment by farfromrefug** [comment]
@mmeven sure thing will fix this!

**Comment by farfromrefug** [comment]
@mmeven published 4.0.7

**Comment by mmeven** [comment]
Sorry for the late answer, thanks for the fix it was useful !
