### ISSUE TITLE
TNSIMageModule has not been processed by ngcc or not compatible with Angular Ivy

### ISSUE THREAD

**Issue by Arslan-Munir** [nativescript-community/ui-image#30]
### Which platform(s) does your issue occur on?
- iOS/Android/Both 
- Android API versions 29
- emulator or device. What type of device? It's OPPO A57

### Please, provide the following version numbers that your issue occurs with:
- CLI: 7.0.3
- Plugin(s): 3.0.12

I am trying to integrate nativescript image with {N} 7.0.3. But I got this error at compile time.
I guess that the version 3.0.12 of nativescript-image is not compatible with 7.0.3.
How can I overcome this error?

### Describe the steps to reproduce it.
Create app with {N} 7.0.3 and install plugin version 3.0.12.

![image](https://user-images.githubusercontent.com/46858790/92299008-2d11cd00-ef68-11ea-920f-3255c7fde964.png)

**Comment by farfromrefug** [comment]
Yes not ready yet for n 7.0 will do

**Comment by farfromrefug** [comment]
@Arslan-Munir you need to switch to @nativescript-community/ui-image. Should work fine
