### ISSUE TITLE
Crashing on iOS when scrolling

### ISSUE THREAD

**Issue by keerl** [nativescript-community/ui-image#34]
Found a problem today in my app. I use `ui-image` in a grid scroll view and when I scroll down the list the app will sometimes crashes violently. There is no error shown in the console, and the only way I can get an error is by going into the logs (see attached image).

Demo project is attached.

[ui-image-crash.zip](https://github.com/nativescript-community/ui-image/files/5513321/ui-image-crash.zip)

![Screen Shot 2020-11-09 at 2 09 59 PM](https://user-images.githubusercontent.com/24727492/98597084-ac3bbe00-2295-11eb-97ca-b478c95d26ff.png)

![ezgif com-gif-maker](https://user-images.githubusercontent.com/24727492/98597236-f1f88680-2295-11eb-8fd1-0c2e7330a42d.gif)

**Comment by keerl** [comment]
Oops, it looks like this could be the same issue as https://github.com/nativescript-community/ui-image/issues/32 ? Was never solved though?

**Comment by farfromrefug** [comment]
Using the v8 runtime? Can you try without it?

**Comment by keerl** [comment]
That seems to be the problem. Was using v8 when it was crashing. Switched to `"tns-ios": "6.5.3"` and the problem is gone. Any idea how to fix it w/ v8? Should I report it over there?

**Comment by pboulch** [comment]
Same problem here with ns7 / v8

**Comment by farfromrefug** [comment]
@pboulch @keerl did not really have the time to look at it. But it would be good to report on the v8 runtime repo. THey might have an idea

**Comment by keerl** [comment]
I did report it there https://github.com/NativeScript/ns-v8ios-runtime/issues/81 it may helpful for @pboulch to post on that issue as well.

**Comment by Jaroslav84** [comment]
same issue here when scrolling table of images. ns7 / v8

Seems like the crash in iOS pod sdwebimage @ this function:

- (void)sd_setImageWithURL:(nullable NSURL *)url
          placeholderImage:(nullable UIImage *)placeholder
                   options:(SDWebImageOptions)options
                   context:(nullable SDWebImageContext *)context
                  progress:(nullable SDImageLoaderProgressBlock)progressBlock
                 completed:(nullable SDExternalCompletionBlock)completedBlock

**Comment by farfromrefug** [comment]
@Jaroslav84 @keerl @pboulch please can you try `4.0.14`?

**Comment by Jaroslav84** [comment]
@farfromrefug same story. 

I'm loading 50 images into a tableList (Angular) with small thumbnail png's. After scrolling (on device) it crashes the same way.
![Screenshot 2020-11-17 at 17 28 03](https://user-images.githubusercontent.com/1220870/99419129-0d9a0780-28fc-11eb-9ac6-001222454c0d.png)

**Comment by romandragan** [comment]
@farfromrefug, still crashing for me as well with the `4.0.14`.

**Comment by romandragan** [comment]
Works fine with `@nativescript/ios@7.0.6`.

**Comment by georgemark0v** [comment]
still crash 
"@nativescript/ios": "^7.0.6
"@nativescript-community/ui-image": "^4.0.14"

**Comment by farfromrefug** [comment]
@georgemark0v try to remove platforms/node_modules/hooks and build again

**Comment by keerl** [comment]
Also confirming this fixed the issue. Good to close.

**Comment by georgemark0v** [comment]
> @georgemark0v try to remove platforms/node_modules/hooks and build again

Solved. Thanks.
