### ISSUE TITLE
nativescript-image modul - wrong inclusions found

### ISSUE THREAD

**Issue by markosole** [nativescript-community/ui-image#36]
Hi all,

I have migrated one of my projects to nativescript 7 and during build time I came across of error which reported that
ERROR in ../node_modules/nativescript-image/image.js
Module not found: Error: Can't resolve 'tns-core-modules/platform/platform'
@ ../node_modules/nativescript-image/image.js 13:17-62

Which is error in **var platform_1 = require("@nativescript/core/platform/platform");** 

Example code below, file>  node_modules/nativescript-image/image.ios.js

`
var fs = require("@nativescript/core/file-system");
var image_asset_1 = require("@nativescript/core/image-asset");
var image_source_1 = require("@nativescript/core/image-source");
var platform_1 = require("@nativescript/core/platform/platform");
var view_1 = require("@nativescript/core/ui/core/view");
var types_1 = require("@nativescript/core/utils/types");
var utils_1 = require("@nativescript/core/utils/utils");
`

### Which platform(s) does your issue occur on?
 
- iOS 
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.0.11

### Please, tell us how to recreate the issue in as much detail as possible. 
I have not tried to reproduce it.

### Is there any code involved? 
 **var platform_1 = require("@nativescript/core/platform/platform");**

Resolution: changing line of code above to: **var platform_1 = require("@nativescript/core/platform");** by removing extra one /platform

**Comment by farfromrefug** [comment]
@markosole there is no such code in that repo. I dont think the error comes from this plugin.
If you can give more info and assure it comes from here i ll reopen

**Comment by markosole** [comment]
I have installed plugin **nativescript-image**, which after installation throws error described above. When I correct /platform/platform part it works perfectly.
NOTE: file effected is node_modules/nativescript-image/image.ios.js

Line of code: 9.

I did remove node_modules and hooks folder, removed nativescript-image plugin and added it again. Than same thing happened.
It could be because of **ns migrate** I have used to migrate old tns 6.x to ns 7.x. 

I am not sure how is image.ios.js generated from ts and what is going on in there.

**Comment by farfromrefug** [comment]
@markosole you are using `nativescript-image` which is not for N 7. Use `@nativescript-community/ui-image`

**Comment by samiul-gtmi** [comment]
@farfromrefug does it mean that `nativescript-image` can't be used in NS7 or NS8 and beyond?
I am facing an error somewhat similar to this, and was wondering about it because the documentation for `nativescript-image` has nothing written about this in it.

**Comment by farfromrefug** [comment]
@samiul-gtmi as mentioned you need to migrate to `@nativescript-community/ui-image`
