### ISSUE TITLE
Stretch setting not working with ImageSource as src

### ISSUE THREAD

**Issue by tomtastico** [nativescript-community/ui-image#37]
### Which platform(s) does your issue occur on?
- Android (not tested in iOS)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.0.11
```
"dependencies": {
    "@angular/animations": "~11.0.0",
    "@angular/common": "~11.0.0",
    "@angular/compiler": "~11.0.0",
    "@angular/core": "~11.0.0",
    "@angular/forms": "~11.0.0",
    "@angular/platform-browser": "~11.0.0",
    "@angular/platform-browser-dynamic": "~11.0.0",
    "@angular/router": "~11.0.0",
    "@nativescript-community/ui-image": "^4.0.18",
    "@nativescript/angular": "~11.0.0",
    "@nativescript/core": "~7.0.0",
    "@nativescript/theme": "~3.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.6.0",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~11.0.0",
    "@nativescript/android": "7.0.1",
    "@nativescript/types": "~7.0.0",
    "@nativescript/webpack": "~3.0.0",
    "@ngtools/webpack": "~11.0.0",
    "typescript": "~4.0.0"
  }
```

### Please, tell us how to recreate the issue in as much detail as possible. 

If you assign a  `ImageSource` as `src` instead of a string path, the `stretch` setting seems to have no effect. Example with both images using `stretch="aspectFill"`.

![image](https://user-images.githubusercontent.com/690217/103021540-98e56900-454a-11eb-8334-6c8a7eb06e23.png)

### Is there any code involved? 

Here is a zip with a basic Angular project showing the issue:
[MyApp.zip](https://github.com/nativescript-community/ui-image/files/5736342/MyApp.zip)

**Comment by farfromrefug** [comment]
@tomtastico thanks i can confirm the issue. Sadly i have no fix for now. I am on the lookout for a solution!

**Comment by tomtastico** [comment]
@farfromrefug I have submitted a possible fix here https://github.com/nativescript-community/ui-image/pull/38

**Comment by tomtastico** [comment]
The bug is not present in iOS

![IMG_0024](https://user-images.githubusercontent.com/690217/103344314-8610ee00-4a8e-11eb-96aa-c742eb97b262.PNG)

**Comment by farfromrefug** [comment]
@tomtastico your issue should now be fixed the right way in the newly published version

**Comment by tomtastico** [comment]
That's great, thanks! I was sure there was a better way :)
