### ISSUE TITLE
Nativescript 6.7.8 compatibility

### ISSUE THREAD

**Issue by sido420** [nativescript-community/ui-image#41]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
I am using Svelte Native and managed to install and use `nativescript-image` (version 3.x I believe). But, `@nativescript-community/ui-image` does not work and throws errors.

There is some info missing below but before I provide that please let me know if its even compatible with my NS version.

### Which platform(s) does your issue occur on?
- Android
- Android 8
- Device (ASUS) 

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.7.8
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/@nativescript/core/package.json` file in your project)
`  "version": "6.5.19"`

- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
```
        "tns-android": {
            "version": "6.5.3"
        }
```

**Comment by farfromrefug** [comment]
the community plugin is only for N 7

**Comment by sido420** [comment]
Thanks.
