### ISSUE TITLE
First images not rendered in view - iOS only

### ISSUE THREAD

**Issue by markosole** [nativescript-community/ui-image#44]
Hi there,

I am using latest version on plugin and on the latest iOS with Xcode etc. and getting problem with rendering first *visible* images in the View. I have RadListView and two columns with 4 items in total per screen. So in total 4 items are displayed when View is loaded, but images are not displaying until I scroll down to see other items (which does render images). When I scroll back up, images (previously not rendered) are displaying properly (they get rendered). 

Android works just fine, default NS <Image> works as well but does not have all features this ui-image module has.

Is there a way to force rendering (re-rendering) or enable/disable cashing or what ever is needed that I can test for iOS?

### Which platform(s) does your issue occur on?
- iOS only, Device, version: 14.6
- iOS only, emulator, version: 14.5 (not tested below)
- Android: **works without problems**

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.0.4
' Plugin version: 4.0.24

  "dependencies": {
    "@nativescript-community/ui-collectionview": "^4.0.29",
    "@nativescript-community/ui-image": "^4.0.24",
    "@nativescript/core": "~8.0.0",
    "@nativescript/geolocation": "^7.1.1",
    "@nstudio/nativescript-cardview": "^2.0.1",
    "@nstudio/nativescript-checkbox": "^2.0.4",
    "@ticnat/nativescript-searchable-select": "^1.0.7",
    "nativescript-appversion": "^1.4.4",
    "nativescript-barcodescanner": "^4.1.1",
    "nativescript-dom": "^2.0.5",
    "nativescript-effects": "^2.0.0",
    "nativescript-fonticon": "^2.0.0",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-google-maps-sdk": "file:nativescript-google-maps-sdk-4.0.0.tgz",
    "nativescript-onesignal": "^1.0.8",
    "nativescript-plugin-firebase": "^10.1.1",
    "nativescript-slides": "^2.3.0",
    "nativescript-sqlite": "^2.3.3",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-ui-listview": "9.1.0",
    "nativescript-ui-sidedrawer": "^9.0.3",
    "nativescript-vibrate": "^4.0.1",
    "rxjs": "^6.4.0",
    "typescript": "^4.2.4"
  },
  "devDependencies": {
    "@nativescript/android": "8.0.0",
    "@nativescript/webpack": "~5.0.0-beta.0",
    "eslint": "~5.8.0",
    "node-sass": "^4.7.1"
  },

### Please, tell us how to recreate the issue in as much detail as possible. 
Run the sample below inside  **<lv:RadListView.listViewLayout>**
   `<iOS><img:Img row="2" col="0" placeholderImageUri="res://noimage" failureImageUri="res://noimage" progressiveRenderingEnabled="true" src="{{ 'https://myap/' + file_url }}"/> </iOS>`

**Comment by farfromrefug** [comment]
please test with listview and not rlv . the issue might be with rlv
