### ISSUE TITLE
Function 'fromFile' and 'fromFileSync' are not working on android

### ISSUE THREAD

**Issue by samiul-gtmi** [nativescript-community/ui-image#45]
### Which platform(s) does your issue occur on?
- Android 11
- device- samsung A20

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.1.4
- Cross-platform modules: 8.0.2
- Runtime(s): 8.1.1
- Plugin(s): 
```
"dependencies": {
    "@nativescript-community/ui-image": "^4.1.0",
    "@nativescript/background-http": "^5.0.2",
    "@nativescript/camera": "^5.0.9",
    "@nativescript/core": "8.0.2",
    "@nativescript/imagepicker": "^1.0.5",
    "@nativescript/localize": "^5.0.4",
    "@nativescript/theme": "^3.0.2",
    "install": "^0.13.0",
    "nativescript-barcodescanner": "4.1.2",
    "nativescript-carousel": "7.0.1",
    "nativescript-ui-sidedrawer": "~9.0.0",
    "numeral": "^2.0.6",
    "sprintf-js": "^1.1.2",
    "webpack": "^5.64.1",
    "webpack-cli": "^4.9.1"
  },
  "devDependencies": {
    "@nativescript/android": "8.1.1",
    "@nativescript/types": "8.0.0",
    "@nativescript/webpack": "~5.0.1",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "sass": "1.34.0",
    "tslint": "^5.9.1",
    "typescript": "~4.0.0"
  },
```

### Please, tell us how to recreate the issue in as much detail as possible. 
I used 'fromFile' in NS-v6 to upload image from gallery to app. It was working fine in both android and ios. However after upgrading the NS version from NS-v6 to NS-v8, the 'fromFile' no longer works on android, though it works fine with ios. 

Now I came to know that 'fromFile' is deprecated and I should use 'fromFileSync' instead.
So, I modified my code from this snippet below
```
import {ImageSource, fromFile} from 'tns-core-modules/image-source'
 // Android
console.log("Adding from gallery for Android:");

const imageSource:ImageSource =  fromFile(localPath);
const imageHeight:number = imageSource.height;
const imageWidth:number = imageSource.width;
const imageRotationAngle:number = isAndroid ?  imageSource.rotationAngle : null;
```
to this snippet below:
```
import { ImageSource } from '@nativescript/core';
// tried below imports also
// let fromFile = require("@nativescript/core/image-source").fromFile;
// import { fromFile } from '@nativescript/core/image-source';
// let fromFileSync = require("@nativescript/core/ImageSource");
// import { fromFileSync } from '@nativescript/core/image-source';

// Android 
  console.log("Adding from gallery for Android:");
  const imageSource:ImageSource = ImageSource.fromFileSync(localPath);
// I also tried- const imageSource:ImageSource = ImageSource.fromFile(localPath);
  const imageHeight:number = imageSource.height;
  const imageWidth:number = imageSource.width;
  const imageRotationAngle:number = isAndroid ?  imageSource.rotationAngle : null;
```

But nonetheless, it is being problematic. As it is constantly declaring any image file/any uploadable jpg, jpeg or png image files to be invalid format to upload.
Kindly let me know if there is any solution to this. Thanks in advance.

**Comment by farfromrefug** [comment]
@samiul-gtmi how is his related to this plugin?

**Comment by samiul-gtmi** [comment]
Thank you for your reply.

Is it not? after I migrated the previous fresco and image to this plugin, the 'fromFile' and 'fromFileSync' stopped working.
Also, these two issues are regarding the image URI, which I believe is related to image operations. And the image operations are being taken care of by this plugin. 

If you don't think so, then would you care to explain, and suggest me the right action to take?

**Comment by farfromrefug** [comment]
@@samiul-gtmi fromFile is a function from N this is why i say.
And if you migrated your snippet you did not only change this plugin but N too as you were using tns-core-modules.
More details /info/debug is needed. I cant help you with just this

**Comment by samiul-gtmi** [comment]
@farfromrefug Then kindly tell me what do you need, I will present the log before you.

**Comment by farfromrefug** [comment]
@samiul-gtmi First you need to investigate what really is your issue. And if it is on N side or on this plugin side. Then create a simple repro sample project to reproduce the issue.
