### ISSUE TITLE
Failed to build plugin @nativescript-community/ui-image in Nativescript 8

### ISSUE THREAD

**Issue by wontroba666** [nativescript-community/ui-image#46]
hello, on Nativescript 8, Android, after generating the basic application and adding ui-image - it is not possible to build / run the application

i have a bug

BUILD FAILED in 4s
Failed to build plugin @nativescript-community/ui-image : 
Error: Command ./gradlew failed with exit code 1

**Steps to reproduce**:
ns create myCoolApp
tns plugin add @nativescript-community/ui-image
ns run android

Can anyone help me ?

**Comment by wontroba666** [comment]
the older version 4.0.34 works fine

**Comment by farfromrefug** [comment]
@wontroba666 sorry about this one. Just published a new version to fix it. 4.1.2 should be ok

**Comment by wontroba666** [comment]
Thanks! it works ;)
