### ISSUE TITLE
SDWebImage/SDImageTransformer.h file not found

### ISSUE THREAD

**Issue by That90sDev** [nativescript-community/ui-image#47]
### Which platform(s) does your issue occur on?

- iOS 15.2
- emulator 

### Please, provide the following version numbers that your issue occurs with:

- CLI:  8.0.2
- Cross-platform modules: 7.1.0
- Runtime(s): 7.1.1
- Plugin(s): 
- "dependencies": {
    "@master.technology/permissions": "^2.0.1",
    "@nativescript-community/ui-image": "^4.1.4",
    "@nativescript-community/ui-material-bottomsheet": "^5.3.15",
    "@nativescript-community/ui-material-tabs": "^6.2.5",
    "@nativescript-community/ui-pager": "^13.0.34",
    "@nativescript/camera": "^5.0.8",
    "@nativescript/core": "~7.1.0",
    "@nativescript/firebase": "^11.1.0",
    "@nativescript/imagepicker": "^1.0.5",
    "@nativescript/localize": "^5.0.4",
    "@nstudio/nativescript-checkbox": "^2.0.4",
    "@nstudio/nativescript-exoplayer": "^5.0.7",
    "@nstudio/nativescript-floatingactionbutton": "^3.0.4",
    "@nstudio/nativescript-loading-indicator": "^4.1.0",
    "@triniwiz/nativescript-image-zoom": "^4.1.1",
    "@triniwiz/nativescript-socketio": "^5.0.1",
    "@vue/devtools": "^5.3.3",
    "axios": "^0.21.1",
    "lodash": "^4.17.21",
    "nativescript-contacts-lite": "^0.2.7",
    "nativescript-emoji": "^1.1.1",
    "nativescript-google-drive": "^1.0.3",
    "nativescript-mediafilepicker": "^4.0.2",
    "nativescript-plugin-filepicker": "^1.0.0",
    "nativescript-social-share": "^1.6.0",
    "nativescript-statusbar": "^5.0.0",
    "nativescript-telephony": "^1.0.4",
    "nativescript-toast": "^2.0.0",
    "nativescript-ui-listview": "^9.1.4",
    "nativescript-urlhandler": "^1.3.0",
    "nativescript-vue": "^2.8.1",
    "nativescript-vue-devtools": "^1.4.0",
    "nativescript-vue-shadow-ns-7": "^10.1.0",
    "vuex": "^3.5.1"
  },
  "devDependencies": {
    "@babel/core": "~7.1.0",
    "@babel/preset-env": "~7.1.0",
    "@nativescript/android": "8.0.0",
    "@nativescript/ios": "7.1.1",
    "@nativescript/types": "^7.3.0",
    "@nativescript/webpack": "~4.0.0",
    "babel-loader": "~8.0.0",
    "clean-webpack-plugin": "^4.0.0",
    "css-loader": "^5.2.0",
    "nativescript-vue-template-compiler": "~2.8.0",
    "nativescript-worker-loader": "^0.12.1",
    "sass": "^1.49.0",
    "vue-loader": "~15.9.3"
  },

### Please, tell us how to recreate the issue in as much detail as possible. 
Android app is working fine but when i run `ns run ios` its unable to compile, when i open xcode 13 and try to run from there then i get this error `SDWebImage/SDImageTransformer.h file not found`

**Comment by farfromrefug** [comment]
@That90sDev you seem to have a pod issue. ensure :
* pod is up to date
* pod repo is up to date
* make a full clean build

**Comment by That90sDev** [comment]
i am running project on Apple Macbook air M1 chip, i am fairly new to Nativescript , please guide me how i can check my pod is up to date and pod repo is up to date. i tried this command `brew install cocoapods `  i use `ns clean` and run `ns run ios` but issue still exists.

**Comment by farfromrefug** [comment]
@That90sDev you are better of asking in discord. I dont have a M1 and their might be something special to do for it

**Comment by tommag21** [comment]
Hi @That90sDev, I am getting too the "file not found" error on Xcode. Have you found a way to build without errors?

**Comment by farfromrefug** [comment]
@tommag21 did you ask on discord?

**Comment by drangelod** [comment]
In case anyone is having this issue on an M1/2 Macbook for iOS builds, the following worked for me.  Right click on your terminal application in Finder, then click on "Get Info".  Check the "Open using Rosetta" option under the General section. Quit the terminal and re-launch and iOS builds should complete properly again.
