### ISSUE TITLE
On IOS Crash - Cannot set property 'image' of null at _setNativeImage

### ISSUE THREAD

**Issue by louisportalest** [nativescript-community/ui-image#49]
### Which platform(s) does your issue occur on?
- iOS
- iOS 15.4
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.3.2
- Cross-platform modules: 8.3.1
- Runtime(s): 8.3.2
- Plugin(s):   "dependencies": {
    "@angular/animations": "^12.2.5",
    "@angular/common": "^12.2.5",
    "@angular/compiler": "^12.2.5",
    "@angular/core": "^12.2.5",
    "@angular/forms": "^12.2.5",
    "@angular/platform-browser": "^12.2.5",
    "@angular/platform-browser-dynamic": "^12.2.5",
    "@angular/router": "^12.2.5",
    "@master.technology/websockets": "^2.0.3",
    "@nativescript-community/ui-image": "^4.3.2",
    "@nativescript-community/ui-material-bottom-navigation": "^6.0.4",
    "@nativescript-community/ui-material-tabs": "^7.0.15",
    "@nativescript/angular": "^12.2.0",
    "@nativescript/background-http": "^5.0.2",
    "@nativescript/camera": "^5.0.12",
    "@nativescript/core": "^8.1.5",
    "@nativescript/firebase": "^11.1.3",
    "@nativescript/theme": "^3.0.0",
    "@ngrx/effects": "^8.5.2",
    "@ngrx/entity": "^8.5.2",
    "@ngrx/store": "^8.5.2",
    "@ngrx/store-devtools": "^8.5.2",
    "moment": "^2.27.0",
    "moment-timezone": "^0.5.32",
    "nativescript-audio": "^6.2.6",
    "nativescript-dna-deviceinfo": "^3.7.3",
    "nativescript-gif": "^5.0.0",
    "nativescript-taptic-engine": "^2.1.0",
    "nativescript-theme-core": "^2.0.24",
    "nativescript-ui-listview": "^10.1.1",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~7.3.0",
    "underscore": "^1.9.2",
    "util": "^0.12.4",
    "words-to-numbers": "^1.5.1",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^12.2.16",
    "@angular/compiler-cli": "^12.2.5",
    "@nativescript/android": "8.2.2",
    "@nativescript/ios": "8.3.2",
    "@nativescript/types": "~8.2.0",
    "@nativescript/webpack": "~5.0.0",
    "@ngtools/webpack": "^12.2.5",
    "nativescript-worker-loader": "^0.12.1",
    "ts-loader": "^8.0.18",
    "typescript": "~4.3.5"
  },

After i run a full clean build (ns clean), i got this error message and the app crashes whenever i scroll to a picture post with NSImg in a RadListView. Not sure why but before the clean build everything was working fine.

***** Fatal JavaScript exception - application has been terminated.
   *****
  NativeScript encountered a fatal error: Uncaught TypeError: Cannot 
  set property 'image' of null
  at
  _setNativeImage(file: node_modules/@nativescript-community/ui-image
  /index.ios.js:267:12)
  at Img.handleImageLoaded(file: node_modules/@nativescript-community
  /ui-image/index.ios.js:173:21)

I tried updating pod, the ui-image plugin and also nativescript, both also not working. Not sure what causing this.

Here is  the code :

<GridLayout row="0"colSpan="3">
    <NSImg 
        stretch="aspectFill"
        [height]="pv_isBigScreen ? post.postStatus.postPictures[0].displaySize * 2 : post.multiPostDisplaySize"
        [src]="post.postStatus.postPictures[0].url"
        (tap)="pm_openPicturePreview(post.postStatus.postPictures[0], $event)">
      </NSImg>
  </GridLayout>

**Comment by louisportalest** [comment]
> @louisportalest does it work outside of radlistview?

Yes it works outside of radlistview. But previously it work well on radlistview, not sure why it stops working now. i try to display the error from failure event and here what it says : 

Error Domain=SDWebImageErrorDomain Code=2002 "Operation cancelled by user during querying the cache" UserInfo={NSLocalizedDescription=Operation cancelled by user during querying the cache}

**Comment by farfromrefug** [comment]
can't really see what s going on with this. sadly you need to investigate to see which version of which package broke it for you

**Comment by msn444** [comment]
I've started seeing this issue as well. I haven't been able to track down what changed to cause it.

It seems that in my case, the issue occurs on a `NSImg` element that is in a Vue component that is toggled by a `v-if` directive. When the Firebase auth state changes to "logged in", the `v-if` expression resolves to `false` and the component is destroyed. This is the action that causes the crash. Perhaps similar to the OP, where dynamic mounting and destroying of items in the `RadListView` causes the crash?

If I change the `v-if` to a `v-show` (which keeps the component mounted but just hides it rather than destroying it), the problem goes away. I'm not sure if this is a good solution though.

**Comment by farfromrefug** [comment]
@msn444 first v-if in listview template should never be done. Though it does not change the fact that you see a bug ;)
Could you try to replace with a simple `ListView` and see if you still have the issue? That would help pinpoint the issue to `RadListView` or the image plugin.
thanks

**Comment by msn444** [comment]
@farfromrefug Actually in my case there's no listview, Rad or otherwise. The problematic `NSImg` was simply in a component whose visibility was toggled by the Firebase login state, using the `v-if` directive. Changing 'v-if' to 'v-show' solves it for me.

In another case, I have `NSImg` in a component displayed in a list using `v-for`. I haven't seen any problems with this method.

**Comment by farfromrefug** [comment]
@msn444 OK i get it. I might have an idea. Will try a fix

**Comment by farfromrefug** [comment]
@msn444 can you try 4.3.5 ?

**Comment by msn444** [comment]
@farfromrefug That seems to have solved it. Thanks for the ultra fast fix!
