### ISSUE TITLE
v4.3.17 Missing angular type files in NPM

### ISSUE THREAD

**Issue by CalebSWhite** [nativescript-community/ui-image#52]
### Which platform(s) does your issue occur on?
- iOS/Android/Both Angular

### Please, provide the following version numbers that your issue occurs with:

- Plugin(s): "@nativescript-community/ui-image": "4.3.17"

### Please, tell us how to recreate the issue in as much detail as possible. 
Run `npm install` with @nativescript-community/ui-image@4.3.17. When you try to run an angular project using this version you get an error
```
error TS2307: Cannot find module '@nativescript-community/ui-image/angular' or its corresponding type declarations.
import { TNSImageModule } from '@nativescript-community/ui-image/angular';
```

You can see it on npm code brower in the angular folder that 4.3.16 has the type files
(https://www.npmjs.com/package/@nativescript-community/ui-image/v/4.3.16?activeTab=code)
and 4.3.17 doesn't
(https://www.npmjs.com/package/@nativescript-community/ui-image/v/4.3.17?activeTab=code)

**Comment by farfromrefug** [comment]
@CalebSWhite sorry about that! should be fixed in latest

**Comment by CalebSWhite** [comment]
No worries at all @farfromrefug. Thanks for your work!!
