### ISSUE TITLE
ui-zoomimage - initialize property does not exist

### ISSUE THREAD

**Issue by rdlauer** [nativescript-community/ui-image#59]
in app.ts:

```
import * as imageModule from "@nativescript-community/ui-zoomimage";
imageModule.initialize({ isDownsampleEnabled: true });
```

When building:
```
Property 'initialize' does not exist on type 'typeof import("/apps/myapp/node_modules/@nativescript-community/ui-zoomimage/index")'.
```

This is on iOS after `ns clean`.

ui-image works just fine so this is an odd one!

**Comment by farfromrefug** [comment]
@rdlauer thanks for the report. It is a typings issue, the export actually exists just not exported in the typings. will fix it

**Comment by farfromrefug** [comment]
@rdlauer should be released

**Comment by rdlauer** [comment]
Thanks! I wonder if something else is missing though (this is for a core app). Hitting this runtime error:

```
  Uncaught Error: Building UI from XML. @tour/tour-page.xml:13:3
   > Module '@nativescript-community/ui-zoomimage' not found for element '@nativescript-community/ui-zoomimage:Img'.
     > instanceType is not a constructor
```

**Comment by farfromrefug** [comment]
@rdlauer never saw that error. Can't really tell like that

**Comment by rdlauer** [comment]
Hmmm strange. I assume I'm doing this right w/ this in the page tag?

```
xmlns:img="@nativescript-community/ui-zoomimage"
```

and here is an image example:

```
<img:Img src="{{ user_image }}" class="image-profile-small" />
```

**Comment by farfromrefug** [comment]
@rdlauer it is `ZoomImg` and not `Img`. see [here](https://github.com/nativescript-community/ui-image/blob/master/src/zoomimage/index.d.ts#L3)

**Comment by rdlauer** [comment]
omg, how did i miss that? thank you!
