### ISSUE TITLE
itemTap of CollectionView not fired if tapping on ZoomImg image

### ISSUE THREAD

**Issue by rdlauer** [nativescript-community/ui-image#60]
I'm not sure if this is a `ui-collectionview` issue, or a `ui-zoomimage` issue! But the `itemTap` event of a CollectionView does not get fired if the image in the template gets tapped, and it's a `ZoomImg` (regular NS `Image` works fine). In this case, `itemTap` is fired if you tap the label, but not the image:

```
<cv:CollectionView items="{{ items }}" itemTap="{{ itemTap }}" colWidth="50%" rowHeight="140">
	<cv:CollectionView.itemTemplate>
              <StackLayout>
			<img:ZoomImg src="{{ cover_image }}" />
			<Label text="{{ title }}" />
		</StackLayout>
	</cv:CollectionView.itemTemplate>
</cv:CollectionView>
```

**Comment by farfromrefug** [comment]
@rdlauer it is not a bug. It is a behavior. Zoomimg can be zoomed so will catch touch event.
And you should use tap event on a template view instead of itemTap
